# Generated by Django 5.0.7 on 2025-04-27 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('opened', 'Opened'), ('unopened', 'Unopened'), ('clicked', 'CTA Clicked'), ('unseen', 'Cold Lead')], default='sent', max_length=10)),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('opened_date', models.DateTimeField(blank=True, null=True)),
                ('clicked_date', models.DateTimeField(blank=True, null=True)),
                ('tracking_id', models.CharField(max_length=50, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
    ]
