# Generated by Django 5.0.7 on 2025-04-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtracking',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
