# Generated by Django 5.0.7 on 2025-04-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_emailtracking_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtracking',
            name='company_name',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='emailtracking',
            name='description',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='emailtracking',
            name='followers',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='emailtracking',
            name='industry',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='emailtracking',
            name='location',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='emailtracking',
            name='website',
            field=models.URLField(default=0),
        ),
    ]
