# Generated by Django 5.0.7 on 2025-04-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_emailtracking_company_name_emailtracking_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtracking',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtracking',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emailtracking',
            name='followers',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtracking',
            name='industry',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtracking',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailtracking',
            name='website',
            field=models.URLField(),
        ),
    ]
